/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:59e408a0-3eca-4abd-84b3-29432d40cdb2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_0XqJsLxg9",
    "aws_user_pools_web_client_id": "iq1a3t4kkh9h6894c7dufr7n4",
    "oauth": {
        "domain": "vcanmeet-staging.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://master.d1nzulc4sg4n11.amplifyapp.com/profile/",
        "redirectSignOut": "https://master.d1nzulc4sg4n11.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_login_mechanisms": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
